[package]
name = "test-gates"
version = "0.1.0"
edition = "2024"

[lib]
name = "test_gates"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "*"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }